/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.55
 * Generated at: 2020-07-02 01:14:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.include;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class maching_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/include/nav.jsp", Long.valueOf(1593514269039L));
    _jspx_dependants.put("jar:file:/C:/src/jspwork/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/doda/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1592268596561L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<title>Bootstrap Example</title>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css\">\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js\"></script>\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("ul li {\r\n");
      out.write("\toutline: 1px white;\r\n");
      out.write("\tmargin-left: 50px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<nav class=\"navbar navbar-expand-sm bg-danger navbar-dark\">\r\n");
      out.write("\t\t<!-- Brand -->\r\n");
      out.write("\r\n");
      out.write("\t\t<a class=\"navbar-brand\" href=\"/doda/index.jsp\">DODA</a>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Links -->\r\n");
      out.write("\t\t<ul class=\"navbar-nav\">\r\n");
      out.write("\t\t\t<li class=\"nav-item dropdown\"><a class=\"nav-link dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\"><b>採用検索</b></a>\r\n");
      out.write("\t\t\t\t<div class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t<a class=\"dropdown-item\" href=\"/doda/doda?cmd=condition\">\r\n");
      out.write("\t\t\t\t\t<b>詳細条件から探す</b></a> <a class=\"dropdown-item\" href=\"#\"><b>新着求人から探す</b></a> <a class=\"dropdown-item\"\r\n");
      out.write("\t\t\t\t\t\thref=\"#\"><b>求人特集から探す</b></a>\r\n");
      out.write("\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t<li class=\"nav-item dropdown\"><a class=\"nav-link dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\"><b>求人を紹介してもらう</b></a>\r\n");
      out.write("\t\t\t\t<div class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t<a class=\"dropdown-item\" href=\"/doda/doda?cmd=ajact\"><b>エージェントサービス</b></a> <a class=\"dropdown-item\" href=\"/doda/doda?cmd=skauto&id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${prinsipal.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"><b>スカウトサービス</b></a>\r\n");
      out.write("\t\t\t\t</div></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<li class=\"nav-item dropdown\"><a class=\"nav-link dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\"><b>知りたい, 聞きたい</b></b></a>\r\n");
      out.write("\t\t\t\t<div class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t<a class=\"dropdown-item\" href=\"/doda/doda?cmd=QA\"><b>転職Q&A</b></a>\r\n");
      out.write("\t\t\t\t</div></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Dropdown -->\r\n");
      out.write("\t\t\t<li class=\"nav-item dropdown\"><a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbardrop\" data-toggle=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t<b>イベント</b></a>\r\n");
      out.write("\t\t\t\t<div class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t<a class=\"dropdown-item\" href=\"/doda/doda?cmd=event\"><b>イベント一覧</b></a> <a class=\"dropdown-item\" href=\"#\"><b>転職フェア</b></a>\r\n");
      out.write("\t\t\t\t</div></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\t<br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<style>\r\n");
      out.write("div { text-align: center; }\r\n");
      out.write("h1 {\r\n");
      out.write("\tmargin: 0 0 0.25em;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("/* Reset Select */\r\n");
      out.write(".one{\r\n");
      out.write("margin:0 auto; display:flex; justify-content:center;\r\n");
      out.write("}\r\n");
      out.write("select {\r\n");
      out.write("\t-webkit-appearance: none;\r\n");
      out.write("\t-moz-appearance: none;\r\n");
      out.write("\t-ms-appearance: none;\r\n");
      out.write("\tappearance: none;\r\n");
      out.write("\toutline: 0;\r\n");
      out.write("\tbox-shadow: none;\r\n");
      out.write("\tborder: 0 !important;\r\n");
      out.write("\tbackground: #2c3e50;\r\n");
      out.write("\tbackground-image: none;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("/* Remove IE arrow */\r\n");
      out.write("select::-ms-expand {\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("/* Custom Select */\r\n");
      out.write(".select {\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("\twidth: 20em;\r\n");
      out.write("\theight: 3em;\r\n");
      out.write("\tline-height: 3;\r\n");
      out.write("\tbackground: #2c3e50;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("\tborder-radius: .25em;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("select {\r\n");
      out.write("\tflex: 1;\r\n");
      out.write("\tpadding: 0 .5em;\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write(".select::after {\r\n");
      out.write("\tcontent: '\\25BC';\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\ttop: 0;\r\n");
      out.write("\tright: 0;\r\n");
      out.write("\tpadding: 0 1em;\r\n");
      out.write("\tbackground: #34495e;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\tpointer-events: none;\r\n");
      out.write("\t-webkit-transition: .25s all ease;\r\n");
      out.write("\t-o-transition: .25s all ease;\r\n");
      out.write("\ttransition: .25s all ease;\r\n");
      out.write("}\r\n");
      out.write("/* Transition */\r\n");
      out.write(".select:hover::after {\r\n");
      out.write("\tcolor: #f39c12;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"one\">\r\n");
      out.write("<form action=\"/doda/doda?cmd=realyserch\" method=\"post\">\r\n");
      out.write("\t<h1>勤務時間</h1>\r\n");
      out.write("\t<div class=\"select\">\r\n");
      out.write("\t\t<select name=\"time\" id=\"time\">\r\n");
      out.write("\t\t\t<option selected disabled>勤務条件</option>\r\n");
      out.write("\t\t\t<option value=\"1\">8時間以下勤務</option>\r\n");
      out.write("\t\t\t<option value=\"2\">8時間勤務</option>\r\n");
      out.write("\t\t\t<option value=\"3\">8~10時間勤務</option>\r\n");
      out.write("\t\t\t<option value=\"4\">10~12時間勤務</option>\r\n");
      out.write("\t\t\t<option value=\"5\">12時間勤務</option>\r\n");
      out.write("\t\t\t<option value=\"6\">24時間勤務</option>\r\n");
      out.write("\t\t</select>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<br />\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"select\">\r\n");
      out.write("\r\n");
      out.write("\t\t<select name=\"day\" id=\"day\">\r\n");
      out.write("\t\t\t<option selected disabled>休日</option>\r\n");
      out.write("\t\t\t<option value=\"7\">週1日</option>\r\n");
      out.write("\t\t\t<option value=\"8\">週2日</option>\r\n");
      out.write("\t\t\t<option value=\"9\">週3日以上</option>\r\n");
      out.write("\t\t\t<option value=\"10\">休日なし</option>\r\n");
      out.write("\t\t</select>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<br />\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"select\">\r\n");
      out.write("\r\n");
      out.write("\t\t<select name=\"school\" id=\"school\">\r\n");
      out.write("\t\t\t<option selected disabled>最終学歴</option>\r\n");
      out.write("\t\t\t<option value=\"11\">小学校卒業</option>\r\n");
      out.write("\t\t\t<option value=\"12\">中学校卒業</option>\r\n");
      out.write("\t\t\t<option value=\"13\">高等学校卒業</option>\r\n");
      out.write("\t\t\t<option value=\"14\">大学卒業</option>\r\n");
      out.write("\t\t\t<option value=\"15\">大学院卒業</option>\r\n");
      out.write("\t\t\t<option value=\"16\">学校に行ったことなし</option>\r\n");
      out.write("\t\t</select>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<br />\r\n");
      out.write("\t<div class=\"select\">\r\n");
      out.write("\t\t<h1></h1>\r\n");
      out.write("\t\t<select name=\"company\" id=\"slct\">\r\n");
      out.write("\t\t\t<option selected disabled>会社規模</option>\r\n");
      out.write("\t\t\t<option value=\"17\">小企業</option>\r\n");
      out.write("\t\t\t<option value=\"18\">中小企業</option>\r\n");
      out.write("\t\t\t<option value=\"19\">大手企業</option>\r\n");
      out.write("\t\t\t<option value=\"20\">スーパー凄い大手企業</option>\r\n");
      out.write("\t\t</select>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<br />\r\n");
      out.write("\t<div class=\"select\">\r\n");
      out.write("\t\t<select name=\"sigoto\" id=\"sigoto\">\r\n");
      out.write("\t\t\t<option selected disabled>職種</option>\r\n");
      out.write("\t\t\t<option value=\"21\">営業職</option>\r\n");
      out.write("\t\t\t<option value=\"22\">企画、管理</option>\r\n");
      out.write("\t\t\t<option value=\"23\">事務</option>\r\n");
      out.write("\t\t\t<option value=\"24\">販売、サービス</option>\r\n");
      out.write("\t\t\t<option value=\"25\">専門職</option>\r\n");
      out.write("\t\t\t<option value=\"26\">技術(IT,Web)</option>\r\n");
      out.write("\t\t\t<option value=\"27\">奴隷</option>\r\n");
      out.write("\r\n");
      out.write("\t\t</select>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<br />\r\n");
      out.write("\t<div class=\"select\">\r\n");
      out.write("\t\t<select name=\"area\" id=\"area\">\r\n");
      out.write("\t\t\t<option selected disabled>地域</option>\r\n");
      out.write("\t\t\t<option value=\"28\">北海道</option>\r\n");
      out.write("\t\t\t<option value=\"29\">大阪府</option>\r\n");
      out.write("\t\t\t<option value=\"30\">東京都</option>\r\n");
      out.write("\t\t\t<option value=\"31\">九州</option>\r\n");
      out.write("\t\t\t<option value=\"32\">岩手県</option>\r\n");
      out.write("\t\t\t<option value=\"33\">新潟県</option>\r\n");
      out.write("\t\t\t<option value=\"34\">群馬県</option>\r\n");
      out.write("\t\t\t<option value=\"35\">三重県</option>\r\n");
      out.write("\t\t\t<option value=\"36\">沖縄県</option>\r\n");
      out.write("\t\t\t<option value=\"37\">北朝鮮</option>\r\n");
      out.write("\t\t</select>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<br />\r\n");
      out.write("\t<div class=\"select\">\r\n");
      out.write("\t\t<select name=\"money\" id=\"money\">\r\n");
      out.write("\t\t\t<option selected disabled>年給</option>\r\n");
      out.write("\t\t\t<option value=\"38\">200万円から~</option>\r\n");
      out.write("\t\t\t<option value=\"39\">250万円から~</option>\r\n");
      out.write("\t\t\t<option value=\"40\">300万円から~</option>\r\n");
      out.write("\t\t\t<option value=\"41\">350万円から~</option>\r\n");
      out.write("\t\t\t<option value=\"42\">400万円から~</option>\r\n");
      out.write("\t\t\t<option value=\"43\">450万円から~</option>\r\n");
      out.write("\t\t\t<option value=\"44\">500万円から~</option>\r\n");
      out.write("\t\t\t<option value=\"45\">550万円から~</option>\r\n");
      out.write("\t\t\t<option value=\"46\">600万円以上</option>\r\n");
      out.write("\t\t\t<option value=\"47\">年給なし</option>\r\n");
      out.write("\t\t</select>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<br />\r\n");
      out.write("\r\n");
      out.write("\t<button class=\"btn btn-primary\" width=\"80\" height=\"40\" style=\"margin-bottom: 3px;\"><b>この条件で探してみます</b></button>\r\n");
      out.write("\t</form>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
